version: '3.8'
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: nestjs
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data